apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    app.kubernetes.io/name: quotes-app
    app.kubernetes.io/component: api
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP