apiVersion: v1
kind: Service
metadata:
  name: data
  labels:
    app.kubernetes.io/name: quotes-app
    app.kubernetes.io/component: database
spec:
  selector:
    app: data
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP