apiVersion: v1
kind: Secret
metadata:
  name: quotes-secret
  labels:
    app.kubernetes.io/name: quotes-app
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root@data:3306/mydatabase"
  MYSQL_DATABASE: "mydatabase"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DB_HOST: "data"
  MYSQL_USER_PASSWORD: "root"